//! Emits the checked-in mdBook contract reference from live plugin metadata.

use grass_app::{App, PluginContract};
use grass_io::{DumpPlugin, RawFrameWriter, RunPlugin, SimClockPlugin, TermOutPlugin};
use oscillator_demo::OscillatorPlugin;

const RUSTDOC: &str = "https://docs.rs/grass_app";
const SOURCE: &str = "https://192.168.4.35/elizabeth-suehr/grass/src/branch/main";

fn list(values: &[String]) -> String {
    if values.is_empty() {
        "—".to_string()
    } else {
        values.join("; ")
    }
}

fn source_link(source: &str) -> String {
    let mut parts = source.splitn(3, ':');
    let path = parts.next().unwrap_or(source);
    let line = parts.next().unwrap_or("");
    format!("[`{source}`]({SOURCE}/{path}#L{line})")
}

fn rustdoc(plugin_name: &str) -> &str {
    match plugin_name.split("::").next().unwrap_or("grass_app") {
        "grass_io" => "https://docs.rs/grass_io",
        "oscillator_demo" => "https://docs.rs/oscillator_demo",
        _ => RUSTDOC,
    }
}

fn render_plugin(out: &mut String, plugin: &PluginContract) {
    out.push_str(&format!("## `{}`\n\n", plugin.plugin_name));
    let rustdoc = rustdoc(&plugin.plugin_name);
    out.push_str(&format!("Rust API: [{rustdoc}]({rustdoc}).\n\n"));
    out.push_str("| Contract | Declared value |\n|---|---|\n");
    let deps: Vec<_> = plugin
        .dependencies
        .iter()
        .map(|d| d.name.clone().unwrap_or_else(|| format!("{:?}", d.type_id)))
        .collect();
    let provides: Vec<_> = plugin.provides.iter().map(ToString::to_string).collect();
    let requires: Vec<_> = plugin.requires.iter().map(ToString::to_string).collect();
    out.push_str(&format!("| Dependencies | {} |\n", list(&deps)));
    out.push_str(&format!(
        "| Provides capabilities | {} |\n",
        list(&provides)
    ));
    out.push_str(&format!(
        "| Requires capabilities | {} |\n",
        list(&requires)
    ));
    out.push_str(&format!(
        "| Schedule participation | {} |\n",
        list(&plugin.metadata.schedule_labels)
    ));
    out.push_str(&format!(
        "| Public extension points | {} |\n",
        list(&plugin.metadata.extension_points)
    ));
    out.push_str(&format!(
        "| Exchange ports / wire types | {} |\n\n",
        list(&plugin.metadata.exchange_contracts)
    ));
    if let Some(config) = &plugin.metadata.config {
        out.push_str(&format!("### `[{}]` configuration\n\n", config.section));
        out.push_str(&config.narrative);
        out.push_str("\n\n| Field | Type | Default | Required | Source |\n|---|---|---|---|---|\n");
        for field in &config.fields {
            let default = field.default.as_deref().unwrap_or("—");
            out.push_str(&format!(
                "| `{}` | `{}` | `{}` | {} | {} |\n",
                field.name,
                field.ty,
                default,
                field.required,
                source_link(&field.source)
            ));
        }
        out.push('\n');
    }
}

fn main() {
    let mut app = App::new();
    app.add_plugins(SimClockPlugin);
    app.add_plugins(TermOutPlugin);
    app.add_plugins(DumpPlugin::new(RawFrameWriter));
    app.add_plugins(RunPlugin);
    app.add_plugins(OscillatorPlugin);
    let contracts = app.plugin_contracts();
    let mut out = String::from("# Generated plugin contracts\n\n");
    out.push_str("This page is generated by [`examples/contract_reference/main.rs`](../../../examples/contract_reference/main.rs) from `App::plugin_contracts()` and typed `ConfigDescription` metadata. Do not edit it by hand; `cargo run --example contract_reference > docs/src/reference/generated-contracts.md` refreshes it, and CI rejects drift. It intentionally records mechanical API facts only; scientific interpretation belongs in the surrounding hand-written reference and tutorials.\n\n");
    out.push_str("The sample registers Grass built-ins plus `oscillator_demo`, demonstrating the same downstream-library path: implement `Plugin`, return declarative metadata, and add the plugin to a documentation probe. Ports are application-owned; `oscillator_demo` advertises its stable `PositionPort<Source>` payload for that seam.\n\n");
    for plugin in &contracts.plugins {
        render_plugin(&mut out, plugin);
    }
    print!("{out}");
}
