//! Emits the checked-in mdBook contract reference from live plugin metadata.

use grass_app::{App, PluginContract};
use grass_io::{DumpPlugin, RawFrameWriter, RunPlugin, SimClockPlugin, TermOutPlugin};
use oscillator_demo::OscillatorPlugin;

const SOURCE: &str = "https://github.com/SueHeir/grass/blob/main";
// `oscillator_demo` is introduced by this branch and is not in the public
// GitHub mirror yet.  Use Gitea's canonical source-page URL for its precise
// source links rather than substituting an unrelated repository-root link.
const OSCILLATOR_SOURCE: &str =
    "http://192.168.0.170:8082/SueHeir/grass/src/branch/auto/grass-generated-contract-reference";

fn list(values: &[String]) -> String {
    if values.is_empty() {
        "—".to_string()
    } else {
        values.join("; ")
    }
}

fn source_link(source: &str) -> String {
    let mut parts = source.splitn(3, ':');
    let path = parts.next().unwrap_or(source);
    let line = parts.next().unwrap_or("");
    let url = if path.starts_with("crates/oscillator_demo/") {
        format!("{OSCILLATOR_SOURCE}/{path}#L{line}")
    } else {
        format!("{SOURCE}/{path}#L{line}")
    };
    format!("[`{source}`]({url})")
}

fn plugin_source(plugin_name: &str) -> &str {
    match plugin_name {
        "grass_io::clock::SimClockPlugin" => "crates/grass_io/src/clock.rs",
        "grass_io::dump::DumpPlugin<grass_io::dump::RawFrameWriter>" => {
            "crates/grass_io/src/dump.rs"
        }
        "grass_io::run::RunPlugin" => "crates/grass_io/src/run.rs",
        "grass_io::term_out::TermOutPlugin" => "crates/grass_io/src/term_out.rs",
        "oscillator_demo::OscillatorPlugin" => "crates/oscillator_demo/src/lib.rs",
        _ => "crates/grass_app/src/plugin.rs",
    }
}

fn render_plugin(out: &mut String, plugin: &PluginContract) {
    out.push_str(&format!("## `{}`\n\n", plugin.plugin_name));
    let source = plugin_source(&plugin.plugin_name);
    let source_url = if source.starts_with("crates/oscillator_demo/") {
        format!("{OSCILLATOR_SOURCE}/{source}")
    } else {
        format!("{SOURCE}/{source}")
    };
    out.push_str(&format!("Rust API source: [`{source}`]({source_url}).\n\n"));
    out.push_str("| Contract | Declared value |\n|---|---|\n");
    let deps: Vec<_> = plugin
        .dependencies
        .iter()
        .map(|d| d.name.clone().unwrap_or_else(|| format!("{:?}", d.type_id)))
        .collect();
    let provides: Vec<_> = plugin.provides.iter().map(ToString::to_string).collect();
    let requires: Vec<_> = plugin.requires.iter().map(ToString::to_string).collect();
    out.push_str(&format!("| Dependencies | {} |\n", list(&deps)));
    out.push_str(&format!(
        "| Provides capabilities | {} |\n",
        list(&provides)
    ));
    out.push_str(&format!(
        "| Requires capabilities | {} |\n",
        list(&requires)
    ));
    out.push_str(&format!(
        "| Schedule participation | {} |\n",
        list(&plugin.metadata.schedule_labels)
    ));
    out.push_str(&format!(
        "| Public extension points | {} |\n",
        list(&plugin.metadata.extension_points)
    ));
    out.push_str(&format!(
        "| Exchange ports / wire types | {} |\n\n",
        list(&plugin.metadata.exchange_contracts)
    ));
    if let Some(config) = &plugin.metadata.config {
        out.push_str(&format!("### `[{}]` configuration\n\n", config.section));
        out.push_str(&config.narrative);
        out.push_str("\n\n| Field | Type | Default | Required | Source |\n|---|---|---|---|---|\n");
        for field in &config.fields {
            let default = field.default.as_deref().unwrap_or("—");
            out.push_str(&format!(
                "| `{}` | `{}` | `{}` | {} | {} |\n",
                field.name,
                field.ty,
                default,
                field.required,
                source_link(&field.source)
            ));
        }
        out.push('\n');
    }
}

fn main() {
    let mut app = App::new();
    app.add_plugins(SimClockPlugin);
    app.add_plugins(TermOutPlugin);
    app.add_plugins(DumpPlugin::new(RawFrameWriter));
    app.add_plugins(RunPlugin);
    app.add_plugins(OscillatorPlugin);
    let contracts = app.plugin_contracts();
    let mut out = String::from("# Generated plugin contracts\n\n");
    out.push_str("This page is generated by [`examples/contract_reference/main.rs`](../../../examples/contract_reference/main.rs) from `App::plugin_contracts()` and typed `ConfigDescription` metadata. Do not edit it by hand; `cargo run --example contract_reference > docs/src/reference/generated-contracts.md` refreshes it, and CI rejects drift. It intentionally records mechanical API facts only; scientific interpretation belongs in the surrounding hand-written reference and tutorials.\n\n");
    out.push_str("The sample registers Grass built-ins plus `oscillator_demo`, demonstrating the same downstream-library path: implement `Plugin`, return declarative metadata, and add the plugin to a documentation probe. Ports are application-owned; `oscillator_demo` advertises its stable `PositionPort<Source>` payload for that seam.\n\n");
    for plugin in &contracts.plugins {
        render_plugin(&mut out, plugin);
    }
    println!("{}", out.trim_end());
}
